### ISSUE TITLE
Memory leak due to useless Unwrap usage

### ISSUE THREAD

**Issue by SlimShaggy** [luigiberrettini/NLog.Targets.Syslog#140]
The syslog target is leaking memory under .Net Framework 4.6.1. UnwrapPromise objects keep accumulating on the heap. I've created a simple test app that runs an endless loop writing to nlog every 10 ms, and the amount of these UnwrapPromise objects is increasing monotonously while it's running, together with memory used.
![syslogtest](https://user-images.githubusercontent.com/5750704/42167404-b049fbfe-7e16-11e8-87c6-95fd3f01c2cd.png)
The dump taken on our server has shown over 8 million of these UnwrapPromise objects by the time it started to run out of memory. Commenting out the syslog target in nlog.config prevents this memory leak.
I'm attaching the test app that reproduces the issue.
[SyslogTest.zip](https://github.com/luigiberrettini/NLog.Targets.Syslog/files/2155466/SyslogTest.zip)

**Comment by luigiberrettini** [comment]
Did you see if the memory was decreasing after delivering all messages?
The target is based on TPL and uses Unwrap: commenting it removes the usage of TPL and unwrap.

Please look also at https://github.com/luigiberrettini/NLog.Targets.Syslog/issues/101#issuecomment-351745991.

**Comment by SlimShaggy** [comment]
I use UDP so there's no way for the program to know whether the messages were delivered, it's a "fire-and-forget" scenario. I modified the test app so that it sends 5000 messages only and then keeps running the loop without sending anything. After it had finished sending all messages there were 4999 UnwrapPromises, and they never got any lower. The memory was not released, although all those messages were successfully received by my syslog server.
![syslogtest5000](https://user-images.githubusercontent.com/5750704/42171647-7d4e00f4-7e22-11e8-9270-64ba18105c28.png)
The modified test app: [SyslogTest5000.zip](https://github.com/luigiberrettini/NLog.Targets.Syslog/files/2155726/SyslogTest5000.zip)

**Comment by luigiberrettini** [comment]
Can you try using the test application and seeing it the issue is still happening?

Can you provide a GitHub repo with your application?

**Comment by SlimShaggy** [comment]
Yes, the issue is still happening. My test application is available at https://github.com/SlimShaggy/SyslogTest

**Comment by luigiberrettini** [comment]
This is what I get with latest stable (not beta) NLog and NLog.Targets.Syslog:

![image](https://user-images.githubusercontent.com/4513301/42176490-0c1a8dc2-7e21-11e8-80fa-ca99c7eaec76.png)

**Comment by SlimShaggy** [comment]
Does it mean that it allocated over 2 MB while sending 5000 messages and then released 500 KB after 15 minutes of inactivity? We have almost no periods of inactivity on our production servers, there are ~200 requests per second with ~20 log writes per request.

**Comment by kilroytrout** [comment]
I tried SlimShaggy's test app and I get the same result. And the UnwrapPromise objects don't get GC'd even after waiting an hour after the 5000 messages are sent.

In  ProcessQueueAsync() (AsyncLogger.cs) there is an Unwrap() on a Continuation leading to creation of a proxy (UnwrapPromise) task that won't be observed. The Unwrap() is superfluous in any case, and if you remove it it will get rid of these objects from the heap.
`
                }, token, TaskContinuationOptions.None, TaskScheduler.Current)
                    **.Unwrap();** - remove this

                return tcs.Task;
`
Maybe, like the task created with Task.Delay, these UnwrapPromise tasks have an internal object reference that's preventing GC. I don't know, but the above change does solve the problem.

**Comment by luigiberrettini** [comment]
I implemented async loops with a continuation calling the same function

```csharp
private Task ProcessQueueAsync(MessageBuilder messageBuilder)
{
    return ProcessQueueAsync(messageBuilder, new TaskCompletionSource<object>())
        .ContinueWith(t =>
        {
            InternalLogger.Warn(t.Exception?.GetBaseException(), "ProcessQueueAsync faulted within try");
            return ProcessQueueAsync(messageBuilder);
        }, token, TaskContinuationOptions.ExecuteSynchronously | TaskContinuationOptions.OnlyOnFaulted, TaskScheduler.Current)
        .Unwrap();
}
```

```csharp
private Task ProcessQueueAsync(MessageBuilder messageBuilder, TaskCompletionSource<object> tcs)
{
    if (token.IsCancellationRequested)
        return tcs.CanceledTask();

    try
    {
        var asyncLogEventInfo = queue.Take(token);
        var logEventMsgSet = new LogEventMsgSet(asyncLogEventInfo, buffer, messageBuilder, messageTransmitter);

        logEventMsgSet
            .Build(layout)
            .SendAsync(token)
            .ContinueWith(t =>
            {
                if (t.IsCanceled)
                {
                    InternalLogger.Debug("Task canceled");
                    return tcs.CanceledTask();
                }
                if (t.Exception != null) // t.IsFaulted is true
                    InternalLogger.Warn(t.Exception.GetBaseException(), "Task faulted");
                else
                    InternalLogger.Debug("Successfully sent message '{0}'", logEventMsgSet);
                return ProcessQueueAsync(messageBuilder, tcs);
            }, token, TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Current)
            .Unwrap();

        return tcs.Task;
    }
    catch (Exception exception)
    {
        return tcs.FailedTask(exception);
    }
}
```

```csharp
private Task SendAsync(CancellationToken token, TaskCompletionSource<object> tcs)
{
    if (token.IsCancellationRequested)
        return tcs.CanceledTask();

    var allSent = currentMessage == logEntries.Length;
    if (allSent)
        return tcs.SucceededTask(() => asyncLogEvent.Continuation(null));

    try
    {
        PrepareMessage();

        messageTransmitter
            .SendMessageAsync(buffer, token)
            .ContinueWith(t =>
            {
                if (t.IsCanceled)
                    return tcs.CanceledTask();
                if (t.Exception != null)
                {
                    asyncLogEvent.Continuation(t.Exception.GetBaseException());
                    tcs.SetException(t.Exception);
                    return Task.FromResult<object>(null);
                }
                return SendAsync(token, tcs);
            }, token, TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Current)
            .Unwrap();

        return tcs.Task;
    }
    catch (Exception exception)
    {
        return tcs.FailedTask(exception);
    }
}
```

These loops are simply run without a continuation or awaiting them, therefore:
 - returning a Task seems to be unnecessary
 - having an Unwrap is not necessary even if, to me, it was semantically correct to always return at the same unnested level

Thanks for the hints, I will investigate further

**Comment by luigiberrettini** [comment]
With the changes proposed and your test program I got this:

![image](https://user-images.githubusercontent.com/4513301/42285605-0576dad8-7fa8-11e8-9311-6179711124eb.png)

 - Snapshot 1 = program start
 - Snapshot 2 = after the firs log message
 - Snapshot 7 = after all messages

**Comment by SlimShaggy** [comment]
Looks much better than 30000+ objects on the screenshot in https://github.com/luigiberrettini/NLog.Targets.Syslog/issues/140#issuecomment-401868182 !

**Comment by SlimShaggy** [comment]
Will the fixed version be available via NuGet?
