### ISSUE TITLE
Flush is not performed on LogManager.Flush

### ISSUE THREAD

**Issue by maximuss** [luigiberrettini/NLog.Targets.Syslog#147]
I have just tested out your Syslog extension and i must say it works pretty well.
I do have one issue and that is that if i have a short amount of code with some logs, which make the program end very fast and then it also prevent the syslog in sending all the messages.
I have tried with both LogManager.Flush and/or LogManager.Shutdown(), but it don't seems to have any effect.

I have a small Visual Studio project where the issue is.
Can throttling have any effect? I have no throttling in my config.

[NlogAndSyslog.zip](https://github.com/luigiberrettini/NLog.Targets.Syslog/files/2188421/NlogAndSyslog.zip)

Best Regards
Bjarne Pedersen
Denmark

**Comment by luigiberrettini** [comment]
Take a look at the [branch](https://github.com/luigiberrettini/NLog.Targets.Syslog/tree/flush) I created with the implementation of the flush feature

**Comment by maximuss** [comment]
Hi :)

I will try to see if i can get time to look into it this week, but we are
pretty pressed on resources becouse of summer holidays :)


Med venlig hilsen / Best Regards

Bjarne Pedersen
System Udvikler
Mail: bp@maximuss.dk
Skype:bp@maximuss.dk

"Never argue with an idiot. He will bring you down to his level and beat
you on experience"
- Greg Kinf
“If you argue with an idiot, there are two idiots”
- Unknown


Den man. 30. jul. 2018 kl. 10.04 skrev Luigi Berrettini <
notifications@github.com>:

**Comment by luigiberrettini** [comment]
Hi @maximuss did you have any chance to take a look at the code?

**Comment by luigiberrettini** [comment]
Hi @maximuss did you have any chance to take a look at my code?

**Comment by maximuss** [comment]
Hi,

I have to admit that i dont have - my work closed the it-department and
fired us all. I had not used syslog since then.
But i would see if i can't get it done in my sparetime instead, i have
forgotten everything about it, sorry!

Med venlig hilsen / Best Regards

Bjarne Pedersen
System Udvikler
Mail: bp@maximuss.dk
Skype:bp@maximuss.dk

"Never argue with an idiot. He will bring you down to his level and beat
you on experience"
- Greg Kinf
“If you argue with an idiot, there are two idiots”
- Unknown


Den lør. 8. sep. 2018 kl. 14.17 skrev Luigi Berrettini <
notifications@github.com>:
