### ISSUE TITLE
VS for Mac does not copy lib to Xamarin app bundle

### ISSUE THREAD

**Issue by dadloo** [luigiberrettini/NLog.Targets.Syslog#150]
If you use this package in Xamarin.iOS make sure this library is copied into final app bundle.

This is not an issue. But more like suggestion that could be put in readme so people with the same problem can find and see the solution.

**Problem**: If the package is not properly copied into app bundle, the configuration is not loaded properly (InitializeSucceeded is false).

**Solution**: Just use something from this package directly in code. For example:
```csharp
var tmp = SyslogTarget();
```

**Note**: I am developing in Visual Studio for Mac (so there may be not an issue if you develop on Windows Visual Studio).

**Comment by luigiberrettini** [comment]
I do not think adding code that directly uses the library is a good solution (it works but seem a hack).
If there is another way to force resources (any binary file) to be added to the app bundle?

**Comment by dadloo** [comment]
Yes it is a hack and I do not like it either. But unfortunately your
library is not the only one with this problem.

Even though you flag a library as copy always, it will appear in C# build
but it will not be inside the bundle output. It seems that the process of
optimalization is ... ehm...too good.
It is so 'good' that it does not even recognize transitive dependecies in
some cases.

Maybe there is some option to disable this kind of behaviour but I did not
want to go that way either.

Sorry I could not be more helpful,

Cheers,

Daniela

so 27. 10. 2018 v 16:19 odesílatel Luigi Berrettini <
notifications@github.com> napsal:

**Comment by luigiberrettini** [comment]
I see there are many problems related to copying files to the application bundle and many issues show up when using Visual Studio for Mac:
- https://forums.xamarin.com/discussion/23052/content-files-are-not-copied-into-application-bundle
- https://bugzilla.xamarin.com/show_bug.cgi?id=55147
- https://bugzilla.xamarin.com/show_bug.cgi?id=25569

My suggestion is opening an issue on the Xamarin bug tracker and/or on the VS for Mac one.
