### ISSUE TITLE
Can log level severities cause undesired behavior?

### ISSUE THREAD

**Issue by alexvy86** [luigiberrettini/NLog.Targets.Syslog#163]
I see in the documentation that the `Trace` log level from NLog gets mapped to syslog's `Notice` by default, but that ends up being above `Informational` in the syslog levels and thus `Trace` messages in the app would end up showing in the logs even if we set the NLog logging level to `Debug` or `Info`, no? I understand that changing all the mappings to be able to put `Trace` at the bottom would be a major breaking change and it's something every application should decide if it wants to do, but maybe it makes sense to document that the default mappings make it so `Trace` is not usable for its original purpose? I.e. logging stuff "below" the `Debug` level.

**Comment by luigiberrettini** [comment]
I introduced the possibility to configure this association in PR #158 and changing the default would introduce a breaking change, something I am not comfortable with.

Moreover, assigning NLog log levels to Syslog severities with a totally different name, only to respect the order on the Syslog side, can generate a lot of confusion and doesn't sound natural to me.

By using NLog configuration a developer can log at the desired NLog level regardless of the target of this logs and therefore of the NLog Target (please open an issue if you experienced a behavior different from this).

To filter out `Trace` log entries it is enough to set `minlevel` appropriately in the NLog `logger` configuration: this shouldn't be done configuring the Syslog server in a way to filter out specific severities.

**Comment by alexvy86** [comment]
Oh you're right, setting the `minlevel` in the NLog logger to `Informational` would filter the `Trace` entries entirely, regardless of what level the syslog server is looking for. The only weird scenario is where the NLog logger is set to `Trace`, the syslog server is only looking for `info` or above (so presumably isn't interested in the app's `Trace` entries), but it will receive `notice` messages that come from the `Trace` entries in the app.

It's more of an edge case that I initially thought, so I guess even the additional documentation isn't that big of a deal :)
