### ISSUE TITLE
Custom Syslog messages are not supported

### ISSUE THREAD

**Issue by southrivertech** [luigiberrettini/NLog.Targets.Syslog#181]
The SysLog interface is working great, thank you for building this connector.

It would be great if there were a configuration option to remove the HeaderBytes prefix from the message line, or to have a complete custom message line (which would not include header bytes).

**Comment by luigiberrettini** [comment]
You made me realize that I implemented something stricter than RFC 3164: thanks for your suggestion!

I was thinking to add two settings to the `rfc3164` section, `outputPri` and `outputHeader`, with default value `true`.
