### ISSUE TITLE
MessageBuilder exception on LogLevel.Off log events

### ISSUE THREAD

**Issue by jstuyck** [luigiberrettini/NLog.Targets.Syslog#190]
Hello, using with .netcore2.0, NLog, i have on the internal log of  Nlog the following warning, it's not blocking.

2019-05-16 10:43:55.7897 Warn Task faulted Exception: System.Collections.Generic.KeyNotFoundException: The given key 'Off' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NLog.Targets.Syslog.MessageCreation.MessageBuilder.PrepareMessage(ByteArray buffer, LogEventInfo logEvent, String logEntry)
   at NLog.Targets.Syslog.LogEventMsgSet.SendAsync(CancellationToken token, TaskCompletionSource`1 tcs)

**Comment by jstuyck** [comment]
Nlog configuration is : 

`<target xsi:type="Syslog"
            name="cee-udp" 
            layout=" ${message} ${exception:format=tostring} action: ${aspnet-mvc-action} ${callsite} ">      
       <sl:enforcement>
                <sl:splitOnNewLine>false</sl:splitOnNewLine>
                <sl:transliterate>false</sl:transliterate>
                <sl:replaceInvalidCharacters>false</sl:replaceInvalidCharacters>
                <sl:truncateFieldsToMaxLength>true</sl:truncateFieldsToMaxLength>
                <sl:truncateMessageTo>1024</sl:truncateMessageTo>
            </sl:enforcement>
          <sl:messageCreation>
              <sl:facility>Local1</sl:facility>
              <sl:rfc>Rfc5424</sl:rfc>
                <sl:rfc5424  
                  hostname="${machinename}"                   
                  procId="${processid}" 
                  msgId="${threadid}">     
                <sl:disableBom>true</sl:disableBom>
              </sl:rfc5424>
            </sl:messageCreation>
            <sl:messageSend>
              <sl:protocol>UDP</sl:protocol> 
              <sl:udp>
                <sl:server>127.0.0.1</sl:server>
                <sl:port>514</sl:port>
              </sl:udp>
            </sl:messageSend>
    </target>`

**Comment by luigiberrettini** [comment]
Hi @jstuyck, thanks for reporting the issue!

I was supposing that log events with a `LogLevel.Off` level where not sent to the target, anyway I will prevent this issue from happening filtering out those events [in the SyslogTarget class](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/v5.1.0/src/NLog.Targets.Syslog/SyslogTarget.cs#L61)
