### ISSUE TITLE
No continuation is called on discarded NLog events

### ISSUE THREAD

**Issue by luigiberrettini** [luigiberrettini/NLog.Targets.Syslog#203]
When [`TryAdd`](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/b9df517e502cef466eab35d9f0e156a1ca0bd43a/src/NLog.Targets.Syslog/AsyncLogger.cs#L112) returns `false` the `asyncLogEventInfo.Continuation` should be called

It would be great if @snakefoot could confirm whether a an exception is needed or null is ok:
```csharp
if (!queue.TryAdd(asyncLogEventInfo, timeout, token))
    asyncLogEventInfo.Continuation(<exception OR null>);
```

**Comment by snakefoot** [comment]
When success then you pass `null` as parameter. When failed/discarded then pass `exception` as parameter to `AsyncContinuation`.

**Comment by snakefoot** [comment]
Maybe also a good idea to do this when discarding LogEvents:

`InternalLogger.Warn("[Syslog] Message discarded as AsyncLogger queue is full);`
