### ISSUE TITLE
Logged time and other layout issues

### ISSUE THREAD

**Issue by rj2Skipper** [luigiberrettini/NLog.Targets.Syslog#216]
i'm very new to NLog and am currently replacing my usage of syslog4net with NLog.Targets.Syslog 
but the desired output is not what this Target produces 
issues I'm having (im using Rfc5424, every request i'm haing is supported by the RFC):
- i can't manipulate the logged time: i want the logger to output UTC but it logs LocalTime
- i want to format the output time to 'yyyy-MM-ddTHH:mm:ss.fffZ' (Timezone-identifier by letter not by time-difference)
- using ${threadid} as msgId does not log the id of the thread writes the message but the threaded-logger (<- does this sentence make sense?), threadid in msg produces the right value
- i can't use ${mdlc} in any of the properties but the msg

maybe you could verify my findings and hint me in a direction to solve this

ciao Ralf

**Comment by snakefoot** [comment]
@luigiberrettini Created PR #217 to resolve this.

**Comment by rj2Skipper** [comment]
I confirm, these changes solve my issue with 'msgId' and so on...

i did solve the issue with time by setting the TimeSource: https://github.com/NLog/NLog/wiki/Time-Source
but time-format ist still hardcoded to log microseconds

**Comment by snakefoot** [comment]
Added another commit to PR #217 so one can configure Timestamp-format using NLog-layout.

**Comment by luigiberrettini** [comment]
I think it is better to address the timestamp format issue in another way and in another PR: I will work on this as soon as possible trying to limit the flexibility to what is allowed by RFC 5424.

Do you know @snakefoot if `logEvent.TimeStamp` is always set to a local time e.g. `DateTime.Now`?

**Comment by snakefoot** [comment]
There is no guarantee for the DateTime.Kind of `logEvent.TimeStamp`

**Comment by luigiberrettini** [comment]
> There is no guarantee for the DateTime.Kind of `logEvent.TimeStamp`

With the `FastLocal` default `TimeSource` the `DateTimeKind` is `Local` but the user can specify a different `TimeSource` in the configuration: should we impose the configuration of a `TimeSource` to drive the output or should we allow them to be in different time zones?

**Comment by snakefoot** [comment]
>  Should we allow them to be in different time zones?

Ofcourse the SysLog target should be agnostic to whatever default TimeSource configured for NLog. And do the conversion required by the user. This is why having timestamp as a NLog Layout is so much more flexible, as the user can choose whatever he/she likes (Utc / Local or high / low precision)

**Comment by luigiberrettini** [comment]
I understand your point, but I have to enforce the standard rather than allowing any format, otherwise users will have a lot of issues because of erroneous configurations.

What I would like to understand is if it is reasonable to output in the same timezone of the `TimeSource` or not?

**Comment by luigiberrettini** [comment]
I understand your point, but I have to enforce the standard rather than allowing any format, otherwise users will have a lot of issues because of erroneous configurations.

What I would like to understand is if it is reasonable to output in the same timezone of the `TimeSource` or not.

**Comment by snakefoot** [comment]
Not sure I understand that argument with standards. You have a hardcoded standard, when people decide to divert from the default standard, then I hope they know what they are doing.

Sounds like you are trying to protect yourself from developers, and that is a long hard battle, that is seldom won.

How do you ensure that they don't send something else that an actual existing machine-name for the hostname?

**Comment by luigiberrettini** [comment]
To me whatever is allowed by the standard is fine: if the standard says you can have 1 to 6 fractional digits and I forced 6 it is my fault, but I do not want to allow people to put any format, otherwise all the effort behind the rewrite of the original target doesn't have any sense: any developer could take a UDP target and put the message parts in configuration.

**Comment by luigiberrettini** [comment]
To me this target should allow what is allowed by the standard, not more and, to some extent, not less.
If the standard says you can have 1 to 6 fractional digits and I forced 6 it is my fault, but I do not want to allow people to put any format, otherwise all the effort behind the rewrite of the original target doesn't have any sense: any developer could take a UDP target and put the message parts in configuration.

**Comment by snakefoot** [comment]
@rj2Skipper [NLog.Targets.Syslog](https://www.nuget.org/packages/NLog.Targets.Syslog) ver. 6.0.1 has been released. Thanks to @luigiberrettini

**Comment by luigiberrettini** [comment]
Thanks to @snakefoot for the continuous attention to details and the resulting contributions!
