### ISSUE TITLE
Message contains unwanted data

### ISSUE THREAD

**Issue by pampua84** [luigiberrettini/NLog.Targets.Syslog#219]
When i try to write log on Syslog server the message contains: DateTime Hostname ApplicationName etc, if i want to omit them from Message it si not possible.
The result i expected in Syslog Server is like this:

![image](https://user-images.githubusercontent.com/17255890/77644860-09cb0680-6f62-11ea-8223-152c8480d0b1.png)

no this:

![image](https://user-images.githubusercontent.com/17255890/77645064-64fcf900-6f62-11ea-910e-ebef06097252.png)

Thanks

**Comment by snakefoot** [comment]
Can you show how you configure the Syslog-Target ?

Looks like you have not configured Target-Layout and is using the default instead of:

```xml
<target xsi:type="Syslog" name="cee-udp">
    <layout>${message}</layout>
</target>
```

**Comment by pampua84** [comment]
I have configured mt Syslog-Target as you have suggested, like this:

` <target xsi:type="sl:Syslog" name="syslog" layout="${message}">
      <sl:messageSend>
        <sl:protocol>UDP</sl:protocol>
        <sl:udp>
          <sl:server>127.0.0.1</sl:server>
          <sl:port>514</sl:port>
        </sl:udp>
      </sl:messageSend>`

but the result in Syslog server is like this:

![image](https://user-images.githubusercontent.com/17255890/77905381-7148c500-7286-11ea-9efc-fc3bb5a5339f.png)

the deleted part is the hostname. In addition, there are also strange characters like - - - etc in the message as you can see from the image.

**Comment by snakefoot** [comment]
Ok try configure it like this (Specifying outputHeader=false):

```xml
<target xsi:type="sl:Syslog" name="syslog" layout="${message}">
      <sl:messageCreation>
         <sl:rfc>Rfc3164</sl:rfc>
         <sl:rfc3164>
           <sl:outputHeader>false</sl:outputHeader>
         </sl:rfc5424>
      </sl:messageCreation/>
      <sl:messageSend>
        <sl:protocol>UDP</sl:protocol>
        <sl:udp>
          <sl:server>127.0.0.1</sl:server>
          <sl:port>514</sl:port>
        </sl:udp>
      </sl:messageSend>
</target>
```

**Comment by pampua84** [comment]
I just tried it, but the name of the application is always present in the log as you can see from the image:

![image](https://user-images.githubusercontent.com/17255890/77917171-7e6faf00-729a-11ea-8e38-31f345cafd10.png)

**Comment by snakefoot** [comment]
But now timestamp etc has been removed.


Guess one have to stare some more at the source code to see if the last part of the header can be removed.


Maybe there is a Layout-property for the App-Name that one can assign to empty string, and it will also go away


Sent from my Sony Xperia


---- pampua84 wrote ----


I just tried it, but the name of the application is always present in the log as you can see from the image:

[image]<https://user-images.githubusercontent.com/17255890/77917171-7e6faf00-729a-11ea-8e38-31f345cafd10.png>

**Comment by luigiberrettini** [comment]
Here follows some suggestions.

1. Determine which standard your server is using/expecting: the message sent by an application should be parsed and no time should be shown on the message field
2. Read [documentation](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/849072a880d616255054f09509d809ef18d428a7/README.md) to understand Syslog standards and how to configure this target
3. Use the test applications to understand what is the output

My guess is that your server is configured for RFC 3164 and you haven't chosen which fields to emit after having had a look at the target documentation.

**Comment by luigiberrettini** [comment]
I would expect an empty configuration setting to result in an empty string after a `Layout` is rendered but this doesn't happen 😱

Using empty tag attributes
`<sl:rfc3164 hostname="" tag="" />`
it still outputs the hostname
`<165>Mar 30 18:05:08 HostNameOfMyPC  This is a sample trace message`

Using empty tags
`<sl:rfc3164><sl:hostname></sl:hostname><sl:tag></sl:tag></sl:rfc3164>`
it outputs both hostname and tag
`<165>Mar 30 18:05:41 HostNameOfMyPC NameOfAssembly This is a sample trace message`

If @snakefoot has any idea that would be helpful 😉

**Comment by luigiberrettini** [comment]
One way to do what you want is with a configuration like the following one

```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:sl="http://www.nlog-project.org/schemas/NLog.Targets.Syslog.xsd">
  <extensions>
    <add assembly="NLog.Targets.Syslog"/>
  </extensions>
  <targets>
    <target xsi:type="sl:Syslog" name="syslog3164-tgt">
      <sl:layout xsi:type="SimpleLayout" text=":${message}${exception:format=ToString,StackTrace}" />
      <sl:enforcement>
        <sl:splitOnNewLine>false</sl:splitOnNewLine>
        <sl:transliterate>true</sl:transliterate>
        <sl:replaceInvalidCharacters>true</sl:replaceInvalidCharacters>
        <sl:truncateFieldsToMaxLength>true</sl:truncateFieldsToMaxLength>
        <sl:truncateMessageTo>1024</sl:truncateMessageTo>
      </sl:enforcement>
      <sl:messageCreation>
        <sl:facility>Local4</sl:facility>
        <sl:rfc>Rfc3164</sl:rfc>
        <sl:rfc3164>
          <sl:outputHeader>false</sl:outputHeader>
          <sl:tag>${literal:text=}</sl:tag>
        </sl:rfc3164>
      </sl:messageCreation>
      <sl:messageSend>
        <sl:protocol>UDP</sl:protocol>
        <sl:udp>
          <sl:server>127.0.0.1</sl:server>
          <sl:port>1514</sl:port>
          <sl:reconnectInterval>3</sl:reconnectInterval>
        </sl:udp>
      </sl:messageSend>
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" maxlevel="Debug" writeTo="syslog3164-tgt" />
  </rules>
</nlog>
```

if you do not have a non-alphanumeric character at the beginning of a message (`:` in the layout above), it will be prefixed with a space: the goal of this target is to generate messages with all the parts detailed in the RFC rather than simply compliant (the RFC itself says a message like `Use the BFG!` has extraordinarily little useful information).

I strongly advise you to check the configuration of your server since it should extract the components instead of showing the all in the message.

**Comment by luigiberrettini** [comment]
One way to do what you want is with a configuration like the following one

```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:sl="http://www.nlog-project.org/schemas/NLog.Targets.Syslog.xsd">
  <extensions>
    <add assembly="NLog.Targets.Syslog"/>
  </extensions>
  <targets>
    <target xsi:type="sl:Syslog" name="syslog3164-tgt">
      <sl:layout xsi:type="SimpleLayout" text=":${message}${exception:format=ToString,StackTrace}" />
      <sl:enforcement>
        <sl:splitOnNewLine>false</sl:splitOnNewLine>
        <sl:transliterate>true</sl:transliterate>
        <sl:replaceInvalidCharacters>true</sl:replaceInvalidCharacters>
        <sl:truncateFieldsToMaxLength>true</sl:truncateFieldsToMaxLength>
        <sl:truncateMessageTo>1024</sl:truncateMessageTo>
      </sl:enforcement>
      <sl:messageCreation>
        <sl:facility>Local4</sl:facility>
        <sl:rfc>Rfc3164</sl:rfc>
        <sl:rfc3164>
          <sl:outputHeader>false</sl:outputHeader>
          <sl:tag>${literal:text=}</sl:tag>
        </sl:rfc3164>
      </sl:messageCreation>
      <sl:messageSend>
        <sl:protocol>UDP</sl:protocol>
        <sl:udp>
          <sl:server>127.0.0.1</sl:server>
          <sl:port>1514</sl:port>
          <sl:reconnectInterval>3</sl:reconnectInterval>
        </sl:udp>
      </sl:messageSend>
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" maxlevel="Debug" writeTo="syslog3164-tgt" />
  </rules>
</nlog>
```

if you do not have a non-alphanumeric character at the beginning of a message (`:` in the layout above), it will be prefixed with a space: the goal of this target is to generate messages with all the parts detailed in the RFC rather than simply compliant (the RFC itself says a message like `Use the BFG!` has extraordinarily little useful information).

I strongly advise you to check the configuration of your server since it should extract the components instead of showing them all in the message column.

**Comment by snakefoot** [comment]
Yes specifying both `<sl:outputHeader>` and `<sl:tag>`  for Rfc3164 will remove the entire header:

```xml
        <sl:rfc3164>
          <sl:outputHeader>false</sl:outputHeader>
          <sl:tag></sl:tag>
        </sl:rfc3164>
```
