### ISSUE TITLE
How do I specify a sub path?

### ISSUE THREAD

**Issue by LuvForAirplanes** [luigiberrettini/NLog.Targets.Syslog#257]
For example, my GrayLog server is located at graylog.example.com/logs

**Comment by luigiberrettini** [comment]
Hi @LuvForAirplanes it would be great if you can provide more details like what is you current configuration, what did you try and what didn't work as expected

**Comment by LuvForAirplanes** [comment]
My configuration is nearly identical to the one on in the readme, but I wanted to specify a sub path. I have nginx configured to accept logs at /logs but I wasn't seeing any options to specify it.

I regret being hasty to open this ticket, as I now realize that Nlog has a built in target for syslog. Hopefully this can help others, though.

**Comment by luigiberrettini** [comment]
It would help if you could post the configuration and detail the error you get adding a sub path.

I am not aware of the existence of other NLog [targets](https://nlog-project.org/config/?tab=targets&search=syslog) for Syslog.
