### ISSUE TITLE
using MappedDiagnosticsLogicalContext in syslog-ng

### ISSUE THREAD

**Issue by mbalsam-refind** [luigiberrettini/NLog.Targets.Syslog#258]
Hi, 

I have a REST web service that is called with the userAccountId (uid)

I would like to log the uid and log data to syslog-ng Opensource.  I would like the uid to be a variable much like RFC5424 $FACILITY or $PROGRAM variables. 

I currently set that data for every rest call using 

      MappedDiagnosticsLogicalContext.SetScoped("UserAccountId", msg.UserAccountId);

And I have access to it in log via 

     ${mdlc:item=UserAccountId}. 

Is there any way I can send that to Syslog, that does not involve parsing it out of each line?

**Comment by luigiberrettini** [comment]
I would suggest starting from here:
https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer

Then to detail your configuration, the expected behavior and the actual one

**Comment by mbalsam-refind** [comment]
Thanks for the reply.  Sorry for not making myself clear, I have the MDLC working. The issue is how to take expose that to syslog. 

I have this working 

  MappedDiagnosticsLogicalContext.SetScoped("UserAccountId", msg.UserAccountId);

The only way I see is to use the rfc5424 fields in my nlog.conf file.  But this has very limited expansion capabilities

              <rfc5424>
                  <hostname>${MyHost}</hostname>
                  <appName>${SyslogAppName}</appName>
                  <procId>${mdlc:item=UserAccountId}</procId>
              </rfc5424>

I was also thinking of using the STRUCTURED-DATA  but see a lot of documentation on how to expose it to syslog. 

Unless you have some magic, I think I will need to write a syslog-ng parser. 

Thanks again.

**Comment by mbalsam-refind** [comment]
I see i was thinking about it wrong.  I should not be using the MDLC but use 

https://github.com/NLog/NLog/wiki/EventProperties-Layout-Renderer

// SetProperty will modify the current Logger, so all log calls will have that property
// SetProperty should be avoided, as it will have unexpected side-effects when multiple threads
logger.SetProperty("myProperty", myValue); 
logger.Info("hello");
logger.Info("again"); // will also have "myProperty"

**Comment by mbalsam-refind** [comment]
I found this post  

https://github.com/luigiberrettini/NLog.Targets.Syslog/issues/93

where they show how to specify the structuredData tab in your nlog.config 

And this does not appear to work. 

                  <structuredData>
                      <fromEventProperties type="SimpleLayout" text="${event-properties:item=UserAccountId}" />
                  </structuredData>

In the other posting they show that this works:

<sl:structuredData>
            <sl:fromEventProperties xsi:type="SimpleLayout" text="[app@0 ${all-event-properties:format=[key]=&quot;[value]&quot;:separator= :includeCallerInformation=False}]" />
          </sl:structuredData>

My guess is the [app@0 is an artifact of the github forum and the actual string should be 

 ${all-event-properties:format=[key]=&quot;[value]&quot;:separator= :includeCallerInformation=False}

Thanks

**Comment by snakefoot** [comment]
Know nothing about SysLog-format, but it seems "random" properties should be injected using the `StructuredData` in Rfc5424:

```xml
           <sl:messageCreation>
                <sl:facility>Local4</sl:facility>
                <sl:rfc>Rfc5424</sl:rfc>
                <sl:rfc5424 hostname="${machinename}" appName="${logger}" procId="${processid}" msgId="testMsgId">
                    <sl:structuredData>
                        <sl:sdElement sdId="UserIdentity">
                            <sl:sdParam name="UserAccountId" value="${mdlc:item=UserAccountId}" />
                        </sl:sdElement>
                    </sl:structuredData>
                    <sl:disableBom>false</sl:disableBom>
                </sl:rfc5424>
            </sl:messageCreation>
```

Maybe an alternative solution could be to use [JsonLayout](https://github.com/nlog/nlog/wiki/JsonLayout) or [XmlLayout](https://github.com/NLog/NLog/wiki/XmlLayout) that provides the `IncludeMdlc`-property

**Comment by luigiberrettini** [comment]
If you just want to log that user id you can just perform a `logger.Info(userId)`

If instead you want to have that information in each log entry you should try to configure the layout or any RFC specific field to take advantage of layout renderers.

To do so you need to:
 - read about [layout renderers](https://github.com/nlog/NLog/wiki/Layout-Renderers)
 - read how to use [custom properties](https://github.com/NLog/NLog/wiki/EventProperties-Layout-Renderer) with them
 - configure a console target and a file target so that they work
 - try a similar configuration with this target
 - report the exact configuration and the actual behavior

**Comment by mbalsam-refind** [comment]
I really appreciate the help.  :)   

I have a multi-threaded environment with 100's of users.  If I simply called `logger.Info(userId)` I would not be sure which userId the logline would correlate to. Therefore I'm trying to use the Layout Renderer variation documented here https://github.com/NLog/NLog/wiki/EventProperties-Layout-Renderer#logger-withproperty-or-SetProperty.  

```
 logger.SetProperty("myProperty", myValue);
 logger.Info("hello");
 logger.Info("again"); // will also have "myProperty"
```


It shows that I can set variables for the logger itself. So each log line after the call would include the userAccountId.  Every rest call would overwrite this.  

      logger.SetProperty("UserAccountId", msg.UserAccountId); 

**nlog.conf** 

```
<variable name="StdLayoutSys"  value="${counter}|${level:format=FirstCharacter}|${message}" />

 <target name="EmailListenerSyslog" type="Syslog" >
          <layout type="SimpleLayout" text="${StdLayoutSys}"/>
          <messageCreation>
              <facility>Local4</facility>
              <rfc3164>
              </rfc3164>
              <rfc5424>
                  <hostname>${MyHost}</hostname>
                  <appName>${SyslogAppName}</appName>
                  <procId></procId>
                  <structuredData>
                       <sl:fromEventProperties xsi:type="SimpleLayout" text="${event-properties:item=UserAccountId}" />
              </structuredData>
              </rfc5424>
          </messageCreation>
            <messageSend><protocol>tcp</protocol><tcp><server>${SyslogHost}</server><port>${SyslogPort}</port></tcp></messageSend>
        </target>
```

I have also attempted this variation suggested by @snakefoot SnakeFoot
```
                 <structuredData>
                      <sdElement sdId="refind">
                          <sdParam name="UserAccountId" value="${mdlc:item=UserAccountId}" />
                      </sdElement>
                  </structuredData>

```
**Syslog-ng destination**
```
destination d_logs   {
        file("/var/log/syslog-ng/logs.txt" 
        template("${ISODATE} !${.SDATA.UserAccountId}! $PROGRAM[$PID]:$MESSAGE\n")
        owner("ubuntu") 
        group("ubuntu") 
        perm(0777) 
        ); 
    };

```
I hope this provides all of the background information you require. 

What I had attempted to ask in the last post but unfortunately was unable to clarify. 

Is the call <strucuredData> logic in the nlog.config correct for use with the nlog.syslog plugin? 

This link https://github.com/luigiberrettini/NLog.Targets.Syslog/issues/93  the author says that it DOES NOT WORK? IS THAT TRUE?  

              <structuredData>
                  <sl:fromEventProperties xsi:type="SimpleLayout" text="${event-properties:item=structuredData}" />
              </structuredData>
Many Thanks! :) :)

**Comment by snakefoot** [comment]
> This link #93 the author says that it DOES NOT WORK? IS THAT TRUE?

When you look at the example-config that should work, then it actually replicates the output from using `sl:sdElement` and `sl:sdParam`. Since it automatically renders square-brackets `[` and `]`. 

I'm guessing this config:

```xml
    <sl:structuredData>
        <sl:fromEventProperties xsi:type="SimpleLayout" text="[refind@0 UserAccountId=&quot;${mdlc:item=UserAccountId}&quot;]" />
    </sl:structuredData>
```

Gives the same output as this config:

```xml
    <sl:structuredData>
       <sdElement sdId="refind@0">
          <sdParam name="UserAccountId" value="${mdlc:item=UserAccountId}" />
       </sdElement>
    </sl:structuredData>
```

Instead of asking what is working with your SysLog-server, then it might be easier just to test it? Seems like you have lots of examples try out already.

P.S. Please don't use `Logger.SetProperty`. It will tear your underwear apart, and give you nightmares. Instead use `Logger.WithProperty` or just use [message-templates](https://github.com/NLog/NLog/wiki/How-to-use-structured-logging).

**Comment by mbalsam-refind** [comment]
I have been testing it on syslog. 

If I can use the mdlc then I don't need to use the Logger.SetProperty.  :) 

But if I use your logic 

```
 <sl:structuredData>
        <sl:fromEventProperties xsi:type="SimpleLayout" text="[refind@0 UserAccountId=&quot;${mdlc:item=UserAccountId}&quot;]" />
    </sl:structuredData>

```

Then how should the syslog destination be setup

`        template("${ISODATE} !${.SDATA.refind.UserAccountId}! $PROGRAM[$PID]:$MESSAGE\n")
`

**Comment by snakefoot** [comment]
> Then how should the syslog destination be setup

No idea. Know nothing about syslog-servers. Guess you have to google it unless @luigiberrettini has some wise words.

**Comment by mbalsam-refind** [comment]
What does the @0 do.  Its an array and this is element 0?

**Comment by mbalsam-refind** [comment]
I switched to using the JSON layout and got everything working.. Thanks for the help!!!!

**Comment by snakefoot** [comment]
@mbalsam-refind Can you post your final NLog.config so others can see what you did?
