### ISSUE TITLE
Appsettings / Json Configuration

### ISSUE THREAD

**Issue by ollie10** [luigiberrettini/NLog.Targets.Syslog#269]
Hello!

As I wrote in [another repository](https://github.com/NLog/NLog/issues/4288) I'm trying to configure Nlog only with the **appsettings.json** or anyway a json configuration file.

I tried the nuget packages which works pretty fine with the File target but I couldn't make it work with Syslog, do you have any example of json configuration I could use?

This is what I'm trying (with Papertail). The configuration works without any problems with Xml

```json
"targets": {
	"Papertail": {
		"type": "Syslog",
		"layout": "${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger:shortName=true}|${message} ${exception:format=tostring}",
		"messageCreation": {
			"facility": "Local7",
			"rfc": "Rfc5424",
			"rfc5424": {
				"hostname": "App.${aspnet-environment}",
				"appName": "App"
			},
			"messageSend": {
				"protocol": "TCP",
				"tcp": {
					"server": "logsxxx.papertrailapp.com",
					"port": 123456,
					"tls": {
						"enabled": true
					}
				}
			}
		}
	}
}
```

**Comment by luigiberrettini** [comment]
Hi @ollie10!

Unfortunately I do not have any sample json configuration, but since settings are parsed by the NLog I would suggest enabling the internal logger to collect further information.

**Comment by ollie10** [comment]
I tried, nothing is shown, no error, nothing...

**Comment by luigiberrettini** [comment]
Strange: usually if you set the level you can see all the parsing steps.

I think the `FakeSyslogServer` [configuration](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/v6.0.2/src/FakeSyslogServer/TestAppHelper.cs#L33) can be helpful.

**Comment by snakefoot** [comment]
`messageSend` is not a property of `messageCreation`. Maybe try this instead:

```json
"targets": {
	"Papertail": {
		"type": "Syslog",
		"layout": "${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger:shortName=true}|${message} ${exception:format=tostring}",
		"messageCreation": {
			"facility": "Local7",
			"rfc": "Rfc5424",
			"rfc5424": {
				"hostname": "App.${aspnet-environment}",
				"appName": "App"
			}
                },
		"messageSend": {
			"protocol": "TCP",
			"tcp": {
				"server": "logsxxx.papertrailapp.com",
				"port": 123456,
				"tls": {
					"enabled": true
				}
			}
		}
	}
}
```

Think one need to configure the NLog InternalLogger to Debug-Level to see what happens during parsing. It can also help to enable `throwConfigExceptions`:

```json
  "NLog": {
    "throwConfigExceptions": true,
    "internalLogLevel": "Debug",
    "internalLogFile": "${basedir}/internal-nlog.txt"
  }
```

But the NLog config parser is very forgiving, and usually just skips unexpected settings.

**Comment by ollie10** [comment]
@snakefoot you are right! I mistakenly put **messageSend** node one node deeper than needed. With this modification it works perfectly.

Now my only lasting point is how to remove completely the Nlog.config.
That's the situation, the configuration is set correctly in the **CreateHostBuilder** function, the question is how to replace the code above? The problem: In the **Main** method you won't have access to **EnvironmentName**. This is not the biggest problem but maybe there is a clean way to do it:

 ```csharp
 public static void Main(string[] args)
{
	NLog.Logger logger = NLog.Web.NLogBuilder.ConfigureNLog("Nlog.config").GetCurrentClassLogger();

	try
	{
		logger.Debug("[Admin] Starting the website");
		CreateHostBuilder(args).Build().Run();
	}
	catch (Exception exception)
	{
		//NLog: catch setup errors
		logger.Error(exception, "[Admin] Stopped the website of an exception");
		throw;
	}
	finally
	{
		// Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
		NLog.LogManager.Shutdown();
	}
}

public static IHostBuilder CreateHostBuilder(string[] args) => Host.CreateDefaultBuilder(args)
.ConfigureAppConfiguration((hostContext, configApp) =>
{
	configApp.AddJsonFile("appsettings.json", optional: false);
	configApp.AddJsonFile($"appsettings.{hostContext.HostingEnvironment.EnvironmentName}.json", optional: true);

	IConfigurationRoot config = new ConfigurationBuilder()
		.AddJsonFile("nlog.json", optional: false, reloadOnChange: true)
		.AddJsonFile($"nlog.{hostContext.HostingEnvironment.EnvironmentName}.json", optional: true)
		.AddEnvironmentVariables().Build();

	var logger = NLog.LogManager.Setup().LoadConfigurationFromSection(config).GetCurrentClassLogger();
})
.ConfigureWebHostDefaults(webBuilder =>
{
	webBuilder.UseStartup<Startup>();
}).ConfigureLogging(logging =>
{
	logging.ClearProviders();
	logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
})
	.UseNLog();
}
```

**Comment by luigiberrettini** [comment]
This can probably help:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments

**Comment by snakefoot** [comment]
@ollie10 You could try this:

```c#
public static void Main(string[] args)
{
   var logger = NLog.LogManager.Setup()
                       .LoadConfigurationFromAppSettings()   // Will automatically load environment-specific appsettings.json
                       .GetCurrentClassLogger();

   try
   {
   	logger.Debug("[Admin] Starting the website");
   	CreateHostBuilder(args).Build().Run();
   }
   catch (Exception exception)
   {
   	//NLog: catch setup errors
   	logger.Error(exception, "[Admin] Stopped the website of an exception");
   	throw;
   }
   finally
   {
   	// Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
   	NLog.LogManager.Shutdown();
   }
}

public static IHostBuilder CreateHostBuilder(string[] args) => Host.CreateDefaultBuilder(args)
         .ConfigureAppConfiguration((hostContext, configApp) =>
         {
            configApp.AddJsonFile("appsettings.json", optional: false);
            configApp.AddJsonFile($"appsettings.{hostContext.HostingEnvironment.EnvironmentName}.json", optional: true);
         })
         .ConfigureWebHostDefaults(webBuilder =>
         {
            webBuilder.UseStartup<Startup>();
         })
         .ConfigureLogging(logging =>
         {
            logging.ClearProviders();
            logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
            if (logging.Services?.GetService(typeof(IConfiguration)) is IConfiguration config)
                NLog.LogManager.Setup().LoadConfigurationFromSection(config);   // Reload again just for fun
         })
         .UseNLog();
```

**Comment by snakefoot** [comment]
@ollie10 Did it answer your question?

**Comment by ollie10** [comment]
@snakefoot sorry for the late replay, yes it answer the question! The only drawback that I see is that using this convention you should have the NLog configuration always in the appsettings and you can't put into an external file, but it's just a small issue, nothing to worry about

**Comment by snakefoot** [comment]
You are very welcome to create PullRequest for the Nlog project to improve the integration with Microsoft Extension Logging.


Have already tried adding several doors based on input from people, but still people are not satisfied. I'm reluctant to create more doors myself, because it is confusing for users, when having to choose between 5 different doors


Sent from my Sony Xperia


---- Vincenzo Pucarelli wrote ----


@snakefoot<https://github.com/snakefoot> sorry for the late replay, yes it answer the question! The only drawback that I see is that using this convention you should have the NLog configuration always in the appsettings and you can't put into an external file, but it's just a small issue, nothing to worry about
