### ISSUE TITLE
Infinite retries and potential log entries lost upon delivery failure

### ISSUE THREAD

**Issue by JayBeavers** [luigiberrettini/NLog.Targets.Syslog#284]
**Describe the problem to solve**
My quick read of `MessageTransmitter` is that undelivered messages will infinitely queue in RAM as `SendMessageAsync` recursively calls itself upon delivery failure. This would mean that queues build up to memory exhaustion and pending messages are lost on process exit if I'm reading it correctly.

**Describe the feature proposed**
It would be beneficial to adopt a retry mechanism, potentially with an exponential backoff delay, which is triggered by delivery issues. This target could also use a size and time limited local file system persistence store for messages which were not delivered, so that they can be transmitted when there are no more delivery issues.

**Comment by luigiberrettini** [comment]
Closing this issue after split.

**Comment by JayBeavers** [comment]
Thank you.  Good call splitting into two items.
