### ISSUE TITLE
Delivery issues result in infinite retries

### ISSUE THREAD

**Issue by luigiberrettini** [luigiberrettini/NLog.Targets.Syslog#285]
**Describe the problem to solve**
[SendMessageAsync](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/v6.0.2/src/NLog.Targets.Syslog/MessageSend/MessageTransmitter.cs#L55) recursively calls itself upon delivery failure basically performing infinite retries.

**Describe the feature proposed**
It would be beneficial to adopt a retry mechanism, potentially with an exponential backoff delay.

<br />
See #284 by @JayBeavers

**Comment by JayBeavers** [comment]
Thank you.
