### ISSUE TITLE
Delivery issues can result in lost log entries

### ISSUE THREAD

**Issue by luigiberrettini** [luigiberrettini/NLog.Targets.Syslog#286]
**Describe the problem to solve**
[SendMessageAsync](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/v6.0.2/src/NLog.Targets.Syslog/MessageSend/MessageTransmitter.cs#L55) perform infinite recursive calls upon delivery failure which can result in the loss of log entries.

**Describe the feature proposed**
This target could use a size and time limited local file system persistence store for messages which were not delivered, so that they can be transmitted when there are no more delivery issues.

<br />
See #284 by @JayBeavers

**Comment by luigiberrettini** [comment]
This target does not use Syslog protocol-level acks as in [RFC 3195](https://datatracker.ietf.org/doc/html/rfc3195) or [RELP](https://en.wikipedia.org/wiki/Reliable_Event_Logging_Protocol), therefore the delivery of log entries is [not reliable](https://rainer.gerhards.net/2008/04/on-unreliability-of-plain-tcp-syslog.html) because of the unreliability of UDP and the [issues](https://rainer.gerhards.net/2008/05/why-you-cant-build-reliable-tcp.html) with TCP.

The main problem is that some network connection issues cannot be detected and therefore log messages will be lost without any exception being raised.

I think this is acceptable considering that logging is not to be used for critical needs: many times logging is used for auditing or basic application events tracking purposes which instead should rely on other tools like databases or messaging systems (or targets for them in the last resort).

In my opinion it would not make sense on one side to accept message loss due to the reasons above and on the other side to put a lot of effort in making sure that, when an exception is raised, a persistent store is used:
 - adding the configuration
 - using files or a local DB like [SQLite](https://www.sqlite.org/index.html) or [RocksDB](https://rocksdb.org)
 - making sure entries are unique and the store is time/size limited
 - reloading the entries from the store on application startup
 - sending past log entries handling the impact on the current application session (past messages before/after/mixed/in parallel with new messages)
 - making sure the storage is not impacted by contention and does not impact throughput

That is why I preferred to avoid application issues due to the indefinite grow of the log entries queue by implemented the [throttling](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/3d0086b19598e487b79b8177d7a252205469525f/docs/configuration.md#enforcement-settings) mechanism to allow dropping messages.

**Comment by JayBeavers** [comment]
Understood that logging in general and syslog in particular are not considered to be reliable by default.  Understood that logging shouldn't substitute for an app specific persistent data storage mechanism.

However it's not a common pattern today that logging systems offer a queue or store & forward system for when connectivity is lost.  These days of mobile devices and mobile-first applications, occasional connectivity losses are something we need to plan for.

And while syslogd is generally a server/systems technology in 'normal' use where connectivity loss is rare and catastrophic, this is specifically a bridging library for Windows apps to transmit logs, and Windows apps are frequently found on laptops and tablets that have occasional connectivity as part of their normal usage patterns.

I use this to bridge my Windows app's logs into a centralized reporting system (e.g. Papertrail in my case).  And my Windows app runs on tablets and laptops that are occasionally disconnected.  I'd love to be able to capture those logs, even when the device isn't on Wifi or cellular at the time.  A basic 'store and forward' retransmit should be a relatively straightforward extension to a 'queue and retry' feature -- the only difference is that the queue would be on disk, the queue would be read on startup, and the queue would need to have a maximum entries limiter (simplest) or circular buffer to prevent resource exhaustion in the case of a 'never connected' system.

**Comment by JayBeavers** [comment]
Note:  I first considered whether there was a store and forward 'middleware' for NLog.  I didn't see one and it didn't look like the design of the NLog TargetWithLayout interface was designed to enable retransmission middleware, as the Write method doesn't return a bool success so we can't layer a retransmitter.  Perhaps a different feature request for a different day, I imagine this change would be rather disruptive :-)

**Comment by luigiberrettini** [comment]
> However it's not a common pattern today that logging systems offer a queue or store & forward system for when connectivity is lost

It depends: I do not expect the NLog target for RabbitMQ to lose messages on exception but I expect this to happen when logging to a file.
Moreover, the library was made async to increase performance and the queue was an accidental consequence due to the synchronous nature of the NLog API.

> These days of mobile devices and mobile-first applications, occasional connectivity losses are something we need to plan for.
> And while syslogd is generally a server/systems technology in 'normal' use where connectivity loss is rare and catastrophic, this is specifically a bridging library for Windows apps to transmit logs, and Windows apps are frequently found on laptops and tablets that have occasional connectivity as part of their normal usage patterns.

I think that application developers should be aware of the [fallacies of distributed computing](https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing) and therefore consider the network unreliable.
I do not believe the attention level should vary depending on where software is deployed: connectivity issues should be handled regardless of the application being on a server, on a laptop, or on a mobile device.

Usually, multiple executable/processes are employed to properly handle all failure scenarios and achieve reliable delivery, as for example with the outbox pattern used with messaging solutions.
This is why I see applications, not libraries, as the perfect fit for handling network connectivity issues via local persistent storage and retransmit capabilities.

In your specific case, this can be achieved by switching to something like the [NLog.Targets.Fluentd target](https://github.com/fluent/NLog.Targets.Fluentd) and rely on Fluentd to reliably send log entries to the Syslog server, decoupling the logging phase in the application from the send/retry/restart handling.
